spring:
    application:
        name: companies-crud-fallback

server:
    servlet:
        context-path: /companies-crud-fallback
    port: 8787

eureka:
    instance:
        instance-id: "${spring.application.name}:${server.port}:${random.value}"
    client:
        service-url:
            defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}