spring:
  application:
    name: report-ms
  profiles:
    default: default
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST:http://ms-config-server:7777}"
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${BROKER_URL:kafka:29092}
      bindings:
        consumerReport-out-0:
          destination: consumerReport

server:
  servlet:
    context-path: /report-ms
  port: 7071
eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.value}"
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://ms-registry-server:8761/eureka/}

fallback:
  uri: ${FALLBACK_URI:http://ms-companies-crud-fallback:8787/companies-crud-fallback/company/{name}}

