spring:
    application:
        name: report-listener
    profiles:
      default: default
    cloud:
      stream:
        Kafka:
          binder:
            brokers: localhost:9092
        function:
          bindings:
            consumerReport-in-O: # consumerReport-out ->consumerReport <-consumerReport-in
              destination: consumerReport
    data:
      mongodb:
        authentication-database: admin
        host: localhost
        port: 27017
        username: sa
        password: sa

    server:
      port: 0
    eureka:
      instance:
        instance-id: "${spring.application.name}:${server.port}:${random.value}"
      client:
        service-url:
          defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
