spring:
  datasource:
    username: ${spring.datasource.username}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
      connection-timeout: ${spring.datasource.hikari.connection-timeout}
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
  application:
    name: companies-crud
  profiles:
    default: prod
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

server:
  servlet:
    context-path: /companies-crud
  port: 8081
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.value}"
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_URL}
        step: 10s
    tracing:
      endpoint: ${OTLP_TRACING_URL}
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s
  endpoints:
    web:
      exposure:
        include: '*'
