spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WilliamCely/microservice-config.git
          default-label: main
          clone-on-start: false
server:
  port: 7777
eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.value}"
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://ms-registry-server:8761/eureka/}

